---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namespace: default

labels:
  - includeSelectors: true
    pairs:
      app: sentiment_data_poller

images:
  - name: sentiment_data_poller
    newName: sentiment_data_poller
    newTag: latest

patchesStrategicMerge:
  - # patch-deployment.yaml
